version : "3.9"

services: 
  app:
    tty: true
    restart: always
    image : ticket-booking
    build : .
    ports :
      - 3000:3000
    env_file :
      - .env
    networks :
      - application
    depends-on :
      db:
        condition : service_healthy
    volumes :
      - .:/src/app
    command: air -c .air.toml

  db:
    image: postgres:alpine
    container_name: ticket-booking-db
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-db:

networks:
  application:
